# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Intern\Documents\GitHub\UV-Sticker\Psoc\UV-Project\UV-Watch_1\UV-Watch_1.cydsn\UV-Watch_1.cyprj
# Date: Sat, 07 Apr 2018 10:56:45 GMT
#set_units -time ns
create_clock -name {SPI_SCBCLK(FFB)} -period 62.5 -waveform {0 31.25} [list [get_pins {ClockBlock/ff_div_1}]]
create_clock -name {ADC_SAR_Seq_1_intClock(FFB)} -period 229.16666666666666 -waveform {0 114.583333333333} [list [get_pins {ClockBlock/ff_div_6}]]
create_clock -name {I2C_SCBCLK(FFB)} -period 625 -waveform {0 312.5} [list [get_pins {ClockBlock/ff_div_2}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFClk} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {SPI_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 7} [list]
create_generated_clock -name {ADC_SAR_Seq_1_intClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 11 23} [list]
create_generated_clock -name {I2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 31 61} [list]


# Component constraints for C:\Users\Intern\Documents\GitHub\UV-Sticker\Psoc\UV-Project\UV-Watch_1\UV-Watch_1.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Intern\Documents\GitHub\UV-Sticker\Psoc\UV-Project\UV-Watch_1\UV-Watch_1.cydsn\UV-Watch_1.cyprj
# Date: Sat, 07 Apr 2018 10:56:41 GMT
