/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_Seq_1.h"
#include "SCB_1.h"
#include "SCB_1_SPI_UART.h"
#include "SCB_1_PINS.h"
#include "SCB_1_SPI_UART_PVT.h"
#include "SCB_1_PVT.h"
#include "SCB_1_BOOT.h"
#include "TCPWM_1.h"
#include "Clock_1.h"
#include "isr_1.h"
#include "ADC_In.h"
#include "ADC_In_aliases.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "LED_2.h"
#include "LED_2_aliases.h"
#include "SW4.h"
#include "SW4_aliases.h"
#include "SW3.h"
#include "SW3_aliases.h"
#include "SW5.h"
#include "SW5_aliases.h"
#include "SW2.h"
#include "SW2_aliases.h"
#include "SW1.h"
#include "SW1_aliases.h"
#include "SCB_2.h"
#include "SCB_2_I2C.h"
#include "SCB_2_PINS.h"
#include "SCB_2_I2C_PVT.h"
#include "SCB_2_PVT.h"
#include "SCB_2_BOOT.h"
#include "BLE_1_gatt.h"
#include "BLE_1.h"
#include "BLE_1_hids.h"
#include "BLE_1_bas.h"
#include "BLE_1_HAL_PVT.h"
#include "BLE_1_STACK_PVT.h"
#include "BLE_1_StackGap.h"
#include "BLE_1_StackGatt.h"
#include "BLE_1_StackGattDb.h"
#include "BLE_1_StackHostMain.h"
#include "BLE_1_StackL2cap.h"
#include "BLE_1_scps.h"
#include "BLE_1_dis.h"
#include "BLE_1_StackGattServer.h"
#include "BLE_1_StackGattClient.h"
#include "BLE_1_Stack.h"
#include "BLE_1_eventHandler.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_Seq_1_intClock.h"
#include "SCB_1_SCBCLK.h"
#include "SCB_1_tx.h"
#include "SCB_1_tx_aliases.h"
#include "SCB_1_rx.h"
#include "SCB_1_rx_aliases.h"
#include "SCB_2_SCBCLK.h"
#include "SCB_2_sda.h"
#include "SCB_2_sda_aliases.h"
#include "SCB_2_scl.h"
#include "SCB_2_scl_aliases.h"
#include "SCB_2_SCB_IRQ.h"
#include "BLE_1_bless_isr.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

