# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Intern\Documents\GitHub\UV-Sticker\Psoc\UV-Project\BLE_FindMe01.cydsn\BLE_FindMe01.cyprj
# Date: Fri, 20 Oct 2017 19:54:14 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\Intern\Documents\GitHub\UV-Sticker\Psoc\UV-Project\BLE_FindMe01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Intern\Documents\GitHub\UV-Sticker\Psoc\UV-Project\BLE_FindMe01.cydsn\BLE_FindMe01.cyprj
# Date: Fri, 20 Oct 2017 19:54:11 GMT
