# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Intern\Documents\GitHub\UV-Sticker\Psoc\UV-Project\BLE_Temp_Test.cydsn\BLE_Temp_Test.cyprj
# Date: Wed, 11 Oct 2017 04:40:09 GMT
#set_units -time ns
create_clock -name {ADC_intClock(FFB)} -period 312.5 -waveform {0 156.25} [list [get_pins {ClockBlock/ff_div_6}]]
create_clock -name {UART_DEB_SCBCLK(FFB)} -period 541.66666666666663 -waveform {0 270.833333333333} [list [get_pins {ClockBlock/ff_div_1}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFCLK} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {ADC_intClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 15 31} [list]
create_generated_clock -name {UART_DEB_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 27 53} -nominal_period 541.66666666666663 [list]


# Component constraints for C:\Users\Intern\Documents\GitHub\UV-Sticker\Psoc\UV-Project\BLE_Temp_Test.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Intern\Documents\GitHub\UV-Sticker\Psoc\UV-Project\BLE_Temp_Test.cydsn\BLE_Temp_Test.cyprj
# Date: Wed, 11 Oct 2017 04:40:06 GMT
