/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SG_AMP.h"
#include "SG1_A.h"
#include "SG1_A_aliases.h"
#include "SG2_A.h"
#include "SG2_A_aliases.h"
#include "GAIN.h"
#include "GAIN_aliases.h"
#include "I2C_TMP116.h"
#include "I2C_TMP116_I2C.h"
#include "I2C_TMP116_PINS.h"
#include "I2C_TMP116_I2C_PVT.h"
#include "I2C_TMP116_PVT.h"
#include "I2C_TMP116_BOOT.h"
#include "BLE_gatt.h"
#include "BLE.h"
#include "BLE_HAL_PVT.h"
#include "BLE_STACK_PVT.h"
#include "BLE_StackGap.h"
#include "BLE_StackGatt.h"
#include "BLE_StackGattDb.h"
#include "BLE_StackHostMain.h"
#include "BLE_StackL2cap.h"
#include "BLE_StackGattServer.h"
#include "BLE_StackGattClient.h"
#include "BLE_Stack.h"
#include "BLE_eventHandler.h"
#include "BLE_custom.h"
#include "ADC.h"
#include "UV5_AMP.h"
#include "UVD_5NEG.h"
#include "UVD_5NEG_aliases.h"
#include "UVD_5POS.h"
#include "UVD_5POS_aliases.h"
#include "UVD_5GAIN.h"
#include "UVD_5GAIN_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "LED_GREEN.h"
#include "LED_GREEN_aliases.h"
#include "LED_RED.h"
#include "LED_RED_aliases.h"
#include "LED_BLUE.h"
#include "LED_BLUE_aliases.h"
#include "RTC.h"
#include "WDT_ISR.h"
#include "V_BATTERY.h"
#include "V_BATTERY_aliases.h"
#include "GUVA.h"
#include "GUVA_aliases.h"
#include "I2C_TMP116_SCBCLK.h"
#include "I2C_TMP116_sda.h"
#include "I2C_TMP116_sda_aliases.h"
#include "I2C_TMP116_scl.h"
#include "I2C_TMP116_scl_aliases.h"
#include "I2C_TMP116_SCB_IRQ.h"
#include "BLE_bless_isr.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

